### ISSUE TITLE
Issue while creating with multiple image

### ISSUE THREAD

**Issue by jijo-citrus** [Ladicle/tcardgen#2]
It is a great tool for me. I created a single twitter card by specifying the MD file name specifically. And my command was like this.
tcardgen -f next.medigy.com/static/font/ \ -o news-content/ \ -t tcardgen/example/template.png \ news-content/healthtechmagazine-why-telehealth-solutions-are-vital-in-a-disaster.md

But I tried the same for multiple images creation which I have a lot of MD files in my content folder. And my command was like this.
tcardgen -f next.medigy.com/static/font/ \ -o news-content/ \ -t tcardgen/example/template.png \ news-content/*.md

And I got the following error message.

Load fonts from "next.medigy.com/static/font/"
Load template from "tcardgen/example/template.png" directory
Failed to generate twitter card for news-content\.png: failed to read page content: read \: The handle is invalid.
Failed to generate twitter card for news-content\.png: failed to read page content: read \: The handle is invalid.
Failed to generate twitter card for news-content\.png: failed to read page content: read \: The handle is invalid.
Failed to generate twitter card for news-content\*.png: open news-content/*.md: The filename, directory name, or volume label syntax is incorrect.
2020/06/30 19:25:27 failed to generate 4 twitter cards

Could you please help me to resolve this issue? Please check the screenshot of the same.

![twitter-card](https://user-images.githubusercontent.com/40203987/86139887-e0e08180-bb0d-11ea-8673-7bc9317607b6.jpg)

**Comment by Ladicle** [comment]
Hi @jijo-citrus, from the terminal prompt, I'm assuming you are running `tcardgen` on a Windows machine, the backslash (`\`) in the sample command is for writing multi-line commands on Linux and macOS. So I think if you remove all backslashes, it'll works.

**Comment by jijo-citrus** [comment]
Hi @Ladicle , Thanks for your help and support. I tried it after removing the backslash. I faced another issue. Please check the same in the given below screenshot.
![tardgen_error](https://user-images.githubusercontent.com/40203987/86783622-31139280-c07e-11ea-8065-cacba80bf7c6.jpg)

**Comment by asiacitrus** [comment]
Hi @Ladicle , Its a great tool and worked well for English content. I am having Arabic text too as description in my MD file and the image generated is having boxes in place of Arabic text. I tried by using Arabic font "Traditional Arabic" in front directory then it throws an error "Failed to load Traditional Arabic".  Please help..

**Comment by Ladicle** [comment]
@jijo-citrus The asterisk(*) is a feature of the fish shell that I use on Mac and Linux, so it probably doesn't work on windows.

Firstly, could you run tcardgen with only one file?

If that works, you might be good to search how to select multiple files on windows. (Unfortunately, I don't have a windows machine, so Ihave no idea.)

**Comment by Ladicle** [comment]
@asiacitrus What is your font file extension? tcardgen only supports `.tty`. BTW, we should talk about this in a separate issue, so could you create another issue?

**Comment by jijo-citrus** [comment]
Thanks for the Help and support. Yes, @Ladicle  You are right. I could create twitter-card image each one by one by specifying the MD file name. And also I created multiple images using "*"  in my windows machine through WSL.
