### ISSUE TITLE
How can I capture custom frontmatter from the MD file?

### ISSUE THREAD

**Issue by jijo-citrus** [Ladicle/tcardgen#4]
Is there any way to capture custom front-matter and display it into the template with out touching the core code? If  so , How can I do that?

**Comment by Ladicle** [comment]
tcardgen doesn't provide that functionality because it complicates the configuration. If you want to do that, use this as a library and write go code :)

**Comment by jijo-citrus** [comment]
Thanks for the same. Ok, I will try to write a code for that. :)
