### ISSUE TITLE
Specifying the output file name

### ISSUE THREAD

**Issue by yyh-gl** [Ladicle/tcardgen#6]
Hi @Ladicle,
thanks for your work of developing this tool.

Today, I have a proposal.

## Proposal

I want  a feature of specifying the output file name.

So, if you set "directory" (ex. `./path/to/directory`) as the value of `-f` option, then output image file name is default one.
On the other hand, if you set "file name" (ex. `./path/to/directory/ogp.png`) as the value of `-f` option, then output image file name is "ogp.png".

This way is compatible.
And, of course, I accept other way.
I hope you will consider it.

**Comment by Ladicle** [comment]
Sounds reasonable, thank you @yyh-gl for your proposal.
Now, tcardgen supports multiple arguments to specify the markdown file, so if the `-o` flag accepts both file and directory, arguments will also accept single or multiple files. Does it work for you?

PS: You mean `-f(--font)` is currently `-o(--outputDir)` flag, right?

**Comment by yyh-gl** [comment]
> so if the -o flag accepts both file and directory, arguments will also accept single or multiple files. Does it work for you?

Sounds good!

> PS: You mean -f(--font) is currently -o(--outputDir) flag, right?

Sorry, it's mistake.
You are right.

If you have no problem, can I take charge of this work?

**Comment by yyh-gl** [comment]
I find a problem of the above proposal.

If you reuse `--outDir` option, I think that `--outDir` has to rename.
But this change is not compatible.

**Comment by Ladicle** [comment]
As you pointed out, `--outDir` is no longer suitable name. So I think it's better to add a new `--output` flag and deprecate the old flag. I mean to display a warning message when using `--outDir`. 

Of course, tcardgen welcomes any contribution if you are interested.

**Comment by yyh-gl** [comment]
Thanks.
I will do following changes.

- Add `--output` option.
  - This option can accept both directory and file.
- Add warning message when use `--outDir`.
  - The message is `Warning: "--outDir" is deprecated and will be removed in v???. Please use "--output".`.

Please let me know if you have other ideas.
(Especially about warning message)

**Comment by Ladicle** [comment]
Sounds nice for the overall design.
For the warning message, since tcardgen hasn't had the version tag yet, I'd like not to specify the removed version.

e.g. This flag will be removed in the future.

**Comment by yyh-gl** [comment]
Sorry, there's one more thing I want to decide.

> tcardgen supports multiple arguments to specify the markdown file

[comment link](https://github.com/Ladicle/tcardgen/issues/6#issuecomment-703187825)

If tcardgen accepts multiple markdown files, how do I specify the output file name?

I think below. How you do you feel about it?

## Draft

Accept multiple output filename separated by commas.

ex. `--output /hogeDir/foo.png,bar.png /fugaDir/content1.md /fugaDir/content2.md`

`content1.md`'s image name is `foo.png`.
`content2.md`'s one is `bar.png`.

**Comment by Ladicle** [comment]
No problem. It's important to design carefully before development :)
tcardgen now allows multiple markdown files as arguments, but it's ok to change. I mean the command allows multiple markdowns when `--output` flag receive directory, and allows only one markdown when the flag receive a file. That would be simpler and easier to combine with other commands.

**Comment by yyh-gl** [comment]
> I mean the command allows multiple markdowns when --output flag receive directory, and allows only one markdown when the flag receive a file.

That's great.
This way is compatible.
I will modify according to your idea.

Thanks.

**Comment by yyh-gl** [comment]
Thanks for your support.
This issue is resolved.
