### ISSUE TITLE
Accept single author

### ISSUE THREAD

**Issue by yyh-gl** [Ladicle/tcardgen#9]
Hi @Ladicle,

I'm bringing the proposal again.

## Proposal

I want to accept both single author and multiple one.

```before.md
author = ["yyh-gl"]
```
↓
```after.md
author = "yyh-gl"
```

On some hoge themes, the UIs change whether it is an array or not.
So, I have to identify A or B.

**Comment by yyh-gl** [comment]
@Ladicle ping

**Comment by Ladicle** [comment]
Sorry for the late reply. It sounds reasonable. Probably it needs to accept multiple type in the parsing process.
I welcome you to contribute again If you are ok :)

**Comment by yyh-gl** [comment]
This issue is fixed.
